# Generated by Django 2.2.10 on 2020-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'Done')])),
            ],
        ),
    ]
