# Generated by Django 2.2.10 on 2020-05-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_createtaskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtaskmodel',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
